[versions]
    min-sdk-version = "24"
    target-sdk-version = "34"
    gradle-plugin-version = "8.1.4"
    kotlin-version = "1.8.10"
    kotlin-compiler-extension-version = "1.5.0"
    androidx-core-ktx-version = "1.12.0"
    androidx-lifecycle-version = "2.6.2"
    compose-bom-version = "2023.10.00"
    compose-activity-version = "1.8.0"
    compose-nav-version = "2.7.4"
    coil-version = "2.4.0"
    retrofit-version = "2.9.0"
    kotlin-serialization-version = "1.9.0"
    json-serialization-version = "1.6.0"
    retrofit-serialization-converter-version = "1.0.0"
    okhttp-version = "4.11.0"
    hilt-version = "2.47"
    hilt-navigation-version = "1.0.0"
    room-version = "2.6.0"
    junit4-version = "4.13.2"
    truth-version = "1.1.3"

[libraries]
    androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx-version" }
    androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-version" }

    compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom-version" }
    compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity-version" }
    compose-ui = { module = "androidx.compose.ui:ui" }
    compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
    compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
    compose-material3 = { module = "androidx.compose.material3:material3" }
    compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
    compose-ui-test-manifest = { module = "androidx.compose.ui:ui-tooling" }
    compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-nav-version" }
    compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-version" }

    coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-version" }

    retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
    reotrfit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization-converter-version" }
    kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json-serialization-version" }
    okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }

    hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
    hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-version" }
    hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-version" }

    room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-version" }
    room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }

    androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.1.5" }
    androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
    androidx-test-compose = { module = "androidx.compose.ui:ui-test-junit4", version = "1.5.4" }

    junit4 = { module = "junit:junit", version.ref = "junit4-version" }
    truth = { module = "com.google.truth:truth", version.ref = "truth-version" }

[bundles]
    androidx = ["androidx-ktx", "androidx-lifecycle-runtime"]
    compose = ["compose-activity", "compose-ui", "compose-graphics", "compose-preview", "compose-material3", "compose-navigation", "compose-lifecycle-runtime"]
    compose-debug = ["compose-ui-tooling", "compose-ui-test-manifest"]
    retrofit = ["retrofit", "reotrfit-serialization", "kotlinx-serialization", "okhttp"]
    hilt = ["hilt-android", "hilt-navigation"]
    ui-tessting = ["androidx-test-ext", "androidx-test-compose", "androidx-test-espresso"]
    unit-testing = ["junit4", "truth"]

[plugins]
    android-application = { id = "com.android.application", version.ref = "gradle-plugin-version" }
    android-library = { id = "com.android.library", version.ref = "gradle-plugin-version" }
    kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
    kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-version" }
    kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-version" }
    hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
